### ISSUE TITLE
maven repo does not contain sources

### ISSUE THREAD

**Issue by ryanobjc** [jstrachan/scopt#4]
It would be nice if the maven publish could include sources, for easier debugging!

Thanks!

**Comment by eed3si9n** [comment]
I just used `publish` command on `sbt`. Do you know if there is something on `sbt` I can override to include the source?

**Comment by eed3si9n** [comment]
I think I found the solution [here](http://code.google.com/p/simple-build-tool/wiki/Publishing).

**Comment by ryanobjc** [comment]
awesome! thanks :-)
