### ISSUE TITLE
Using Flag seems not working

### ISSUE THREAD

**Issue by tonicebrian** [jstrachan/scopt#7]
Hi,

I'm trying to use the flat option but I'm getting results I do not understand. I define the flag as 

```
flag("f","flag","A flag"){(c:Config)=> c.copy(myFlag = true)},
```

and I get the following error

```
[error]  found   : scopt.generic.FlagOptionDefinition[Config => Config]
[error]  required: scopt.generic.OptionDefinition[Config]
```

What I'm doing wrong? Could you provide a test for flag options?

**Comment by eed3si9n** [comment]
The scopt dev has moved to [scopt/scopt](https://github.com/scopt/scopt).
This issue has been reported already, but I didn't realize till now since I had my notification turned off, so hopefully it'll be fixed soon.
